### ISSUE TITLE
Init express

### ISSUE THREAD

**Issue by alexjharrison** [alexjharrison/hackathon-starter#6]
in `/express` with dockerfile

- [x] create user table in pg
- [x] create routes for login/register
- [x] routes point to pg table
- [x] generates jwt for routers

**Comment by elongton** [comment]
======this stuff doesn't work yet, I think the pg_dumpall command isn't working correctly=======
database "auth" added to postgres with table "users". 
File "hackathonstarter1.sql.gz" added to postgres/seed-data/ folder
Readme file in postgres folder contains command for exporting the DB as seed data, we still need to figure out migrations.
================================
**you'll need to locally create database "auth" with table "users"
**add columns "email, encrypted_password, first_name, last_name"

As for express, all should work now.  test the routes:
http://localhost:8000/auth/login
with JSON body:
 {
    "email": "test2@example.com",
    "password": "password123"
 }

http://localhost:8000/auth/register
with JSON body:
 {
    "email": "test3@example.com",
    "password": "password123",
    "first_name": "test",
    "last_name": "test3"
  }
